import CustomPostLink from "../CustomLink/CustomPostLink"

const weddings = [
    {
        bgColor: "bgDark",
        title: "Beata & Paweł",
        details: "Mimo niesprzyjającej aury na zewnątrz udało się wyczarować coś niesamowitego. Prostota, elegancja, geometria, złote dodatki, szarość, zieleń i biel - jesienne wesela mają moc.",
        org: "Agencja Ślubna Czary Marry",
        orgLink: "",
        place: "Pałac Łagów",
        placeLink: "https://palac-lagow.pl/",
        photo: "Ania Kopeć Serdeczności",
        photoLink: "https://serdecznosci.com.pl/",
        flowers: "My Precious",
        flowersLink: "http://myprecious.pl/",
        photos: {
            pic1: require('./OurCouplesPics/BeataPawel/01.jpg').default,
            pic2: require('./OurCouplesPics/BeataPawel/02.jpg').default,
            pic3: require('./OurCouplesPics/BeataPawel/03.jpg').default,
            pic4: require('./OurCouplesPics/BeataPawel/04.jpg').default,
            pic5: require('./OurCouplesPics/BeataPawel/05.jpg').default,
            pic6: require('./OurCouplesPics/BeataPawel/06.jpg').default,
            pic7: require('./OurCouplesPics/BeataPawel/07.jpg').default,
            pic8: require('./OurCouplesPics/BeataPawel/08.jpg').default,
            pic9: require('./OurCouplesPics/BeataPawel/09.jpg').default,
            pic13: require('./OurCouplesPics/BeataPawel/13.jpg').default,
            pic14: require('./OurCouplesPics/BeataPawel/14.jpg').default,
            pic15: require('./OurCouplesPics/BeataPawel/15.jpg').default,
            pic16: require('./OurCouplesPics/BeataPawel/16.jpg').default,
            picVer1: require('./OurCouplesPics/BeataPawel/ver1.jpg').default,
            picVer2: require('./OurCouplesPics/BeataPawel/ver2.jpg').default,
            picVer3: require('./OurCouplesPics/BeataPawel/ver3.jpg').default,
            picVer4: require('./OurCouplesPics/BeataPawel/ver4.jpg').default,
            picVer5: require('./OurCouplesPics/BeataPawel/ver5.jpg').default,
            picVer6: require('./OurCouplesPics/BeataPawel/ver6.jpg').default,
            picVer7: require('./OurCouplesPics/BeataPawel/ver7.jpg').default,
            classNameOne: "twoVertHorizFlipped",
            classNameThree: "twoVertHoriz"
        }
    },
    {
        bgColor: "bgMint",
        title: "Foodtruck Wedding",
        path: "foodtruck-wedding",
        date: "12 lut 2022",
        mainPic: {
            src: require('./OurCouplesPics/FoodtruckWedding/01.jpg').default
        },
        minHeight: true,
        details: "Event branżowy połączony z sesją stylizowaną w stylu slow, czyli tak jak lubimy najbardziej. Garden party odbyło się w pałacowym ogrodzie, w którym stanęły pięknie odrestaurowane stare samochody. Nie zabrakło również dekoracji kwiatowych, stref chilloutu i dobrej muzyki.",
        org: "Agencja Ślubna Czary Marry",
        orgLink: "",
        place: "Pałac Osowa Sień",
        placeLink: "https://www.palacosowasien.com/",
        photo: "Wosiak",
        photoLink: "https://wosiakfotografia.pl/",
        photoTwo: "Wojciech Makula",
        photoLinkTwo: "https://www.wojciechmakula.pl/",
        movie: "Primephoto",
        movieLink: "https://teledyskslubny.pl/",
        flowers: "Pracownia Zieleni",
        flowersLink: "http://pracowniazieleni.pl/",
        photos: {
            pic1: require('./OurCouplesPics/FoodtruckWedding/01.jpg').default,
            pic2: require('./OurCouplesPics/FoodtruckWedding/02.jpg').default,
            pic3: require('./OurCouplesPics/FoodtruckWedding/03.jpg').default,
            pic4: require('./OurCouplesPics/FoodtruckWedding/04.jpg').default,
            pic5: require('./OurCouplesPics/FoodtruckWedding/05.jpg').default,
            pic6: require('./OurCouplesPics/FoodtruckWedding/06.jpg').default,
            pic7: require('./OurCouplesPics/FoodtruckWedding/07.jpg').default,
            pic8: require('./OurCouplesPics/FoodtruckWedding/08.jpg').default,
            pic9: require('./OurCouplesPics/FoodtruckWedding/09.jpg').default,
            pic10: require('./OurCouplesPics/FoodtruckWedding/10.jpg').default,
            pic11: require('./OurCouplesPics/FoodtruckWedding/11.jpg').default,
            pic12: require('./OurCouplesPics/FoodtruckWedding/12.jpg').default,
            pic13: require('./OurCouplesPics/FoodtruckWedding/13.jpg').default,
            pic14: require('./OurCouplesPics/FoodtruckWedding/14.jpg').default,
            pic15: require('./OurCouplesPics/FoodtruckWedding/15.jpg').default,
            pic16: require('./OurCouplesPics/FoodtruckWedding/16.jpg').default,
            picVer1: require('./OurCouplesPics/FoodtruckWedding/ver1.jpg').default,
            picVer2: require('./OurCouplesPics/FoodtruckWedding/ver2.jpg').default,
            picVer3: require('./OurCouplesPics/FoodtruckWedding/ver3.jpg').default,
            picVer4: require('./OurCouplesPics/FoodtruckWedding/ver4.jpg').default,
            picVer5: require('./OurCouplesPics/FoodtruckWedding/ver5.jpg').default,
            picVer6: require('./OurCouplesPics/FoodtruckWedding/ver6.jpg').default,
            classNameOne: "twoVertHoriz",
            classNameTwo: "threeHoriz",
            classNameThree: "twoVertHorizFlipped"
        }
    },
    {
        bgColor: "bgGrey",
        title: "Ewa & Manu",
        details: "To był prawdziwy polsko-hiszpański ogień. Mieszanka kultur i tradycji oraz masa świetnej zabawy. Właśnie dlatego uwielbiamy wesela międzynarodowe.",
        org: "Agencja Ślubna Czary Marry",
        orgLink: "",
        place: "Golden Tulip Magnus",
        placeLink: "https://magnus-bielsko.goldentulip.com/pl/",
        photo: "Jakub Nowotyński",
        photoLink: "https://fotoreportazslubny.com/",
        movie: "BlackHart Film",
        movieLink: "http://www.blackhartfilms.com/",
        flowers: "Hola Studio Flo",
        flowersLink: "https://www.facebook.com/holastudioflo/",
        photos: {
            pic1: require('./OurCouplesPics/EwaManu/01.jpg').default,
            pic2: require('./OurCouplesPics/EwaManu/03.jpg').default,
            pic4: require('./OurCouplesPics/EwaManu/04.jpg').default,
            pic5: require('./OurCouplesPics/EwaManu/05.jpg').default,
            pic6: require('./OurCouplesPics/EwaManu/08.jpg').default,
            pic7: require('./OurCouplesPics/EwaManu/11.jpg').default,
            pic8: require('./OurCouplesPics/EwaManu/09.jpg').default,
            pic9: require('./OurCouplesPics/EwaManu/10.jpg').default,
            pic10: require('./OurCouplesPics/EwaManu/06.jpg').default,
            pic11: require('./OurCouplesPics/EwaManu/07.jpg').default,
            pic12: require('./OurCouplesPics/EwaManu/02.jpg').default,
            pic14: require('./OurCouplesPics/EwaManu/16.jpg').default,
            pic15: require('./OurCouplesPics/EwaManu/17.jpg').default,
            pic17: require('./OurCouplesPics/EwaManu/15.jpg').default,
            pic18: require('./OurCouplesPics/EwaManu/12.jpg').default,
            pic19: require('./OurCouplesPics/EwaManu/13.jpg').default,
            picVer4: require('./OurCouplesPics/EwaManu/ver01.jpg').default,
            classNameTwo: "threeHoriz",
            classNameFive: "threeHorizFlipped"
        }
    },
    {
        bgColor: "bgDark",
        title: "Angelika & Paweł",
        details: "Zamek Książ zachwyca niesamowitą architekturą i historią. Dzięki zaufaniu i otwartości pary oraz niezastąpionej ekipie udało nam się dopisać kolejny, cudowny rozdział tej historii i stworzyć niesamowity klimat.",
        org: "Agencja Ślubna Czary Marry",
        orgLink: "",
        place: "Zamek Książ",
        placeLink: "https://www.ksiaz.walbrzych.pl/",
        photo: "Jam Studio",
        photoLink: "https://jamstudio.pl/",
        photoTwo: "Magdalena Adamczewska",
        photoLinkTwo: "https://www.facebook.com/magdalena.adamczewska",
        movie: "Cameralni",
        movieLink: "http://cameralni.com/",
        flowers: "ArtSize",
        flowersLink: "https://www.artsize.pl/",
        photos: {
            pic1: require('./OurCouplesPics/AngelikaPawel/01.jpg').default,
            pic2: require('./OurCouplesPics/AngelikaPawel/02.jpg').default,
            pic3: require('./OurCouplesPics/AngelikaPawel/03.jpg').default,
            pic4: require('./OurCouplesPics/AngelikaPawel/04.jpg').default,
            pic5: require('./OurCouplesPics/AngelikaPawel/05.jpg').default,
            pic6: require('./OurCouplesPics/AngelikaPawel/06.jpg').default,
            pic7: require('./OurCouplesPics/AngelikaPawel/07.jpg').default,
            pic8: require('./OurCouplesPics/AngelikaPawel/08.jpg').default,
            pic9: require('./OurCouplesPics/AngelikaPawel/09.jpg').default,
            pic10: require('./OurCouplesPics/AngelikaPawel/11.jpg').default,
            pic11: require('./OurCouplesPics/AngelikaPawel/12.jpg').default,
            pic12: require('./OurCouplesPics/AngelikaPawel/10.jpg').default,
            pic16: require('./OurCouplesPics/AngelikaPawel/16.jpg').default,
            pic17: require('./OurCouplesPics/AngelikaPawel/17.jpg').default,
            pic18: require('./OurCouplesPics/AngelikaPawel/18.jpg').default,
            pic19: require('./OurCouplesPics/AngelikaPawel/19.jpg').default,
            picVer1: require('./OurCouplesPics/AngelikaPawel/ver2.jpg').default,
            picVer2: require('./OurCouplesPics/AngelikaPawel/ver4.jpg').default,
            picVer3: require('./OurCouplesPics/AngelikaPawel/ver3.jpg').default,
            picVer6: require('./OurCouplesPics/AngelikaPawel/ver6.jpg').default,
            picVer7: require('./OurCouplesPics/AngelikaPawel/ver7.jpg').default,
            classNameOne: "twoVertHorizFlipped",
            classNameTwo: "threeHoriz",
            classNameThree: "twoVertHoriz",
            classNameFive: "threeHorizFlipped"
        }
    },
    {
        bgColor: "bgPink",
        title: "Olga & Piotr",
        details: "To klimatyczna sesja stylizowana. Połączenie surowych ruin zamku oraz eleganckich dekoracji. Sesja była zorganizowana z myślą o parach, którym Covid-19 pokrzyżował weselne plany.",
        org: "Agencja Ślubna Czary Marry",
        orgLink: "",
        place: "Zamek Sarny",
        placeLink: "http://www.zameksarny.pl/",
        photo: "Małe Szare Studio",
        photoLink: "http://maleszarestudio.pl/",
        movie: "Sakramentalne tak",
        movieLink: "https://www.sakramentalnetak.com/",
        flowers: "Anello Decor",
        flowersLink: "https://www.facebook.com/anellodecor/",
        photos: {
            pic1: require('./OurCouplesPics/OlgaPiotr/01.jpg').default,
            pic2: require('./OurCouplesPics/OlgaPiotr/03.jpg').default,
            pic3: require('./OurCouplesPics/OlgaPiotr/02.jpg').default,
            pic4: require('./OurCouplesPics/OlgaPiotr/04.jpg').default,
            pic5: require('./OurCouplesPics/OlgaPiotr/05.jpg').default,
            pic6: require('./OurCouplesPics/OlgaPiotr/07.jpg').default,
            pic7: require('./OurCouplesPics/OlgaPiotr/06.jpg').default,
            pic14: require('./OurCouplesPics/OlgaPiotr/14.jpg').default,
            pic15: require('./OurCouplesPics/OlgaPiotr/15.jpg').default,
            pic16: require('./OurCouplesPics/OlgaPiotr/16.jpg').default,
            pic17: require('./OurCouplesPics/OlgaPiotr/17.jpg').default,
            picVer1: require('./OurCouplesPics/OlgaPiotr/ver3.jpg').default,
            picVer2: require('./OurCouplesPics/OlgaPiotr/ver2.jpg').default,
            picVer3: require('./OurCouplesPics/OlgaPiotr/ver1.jpg').default,
            picVer4: require('./OurCouplesPics/OlgaPiotr/ver4.jpg').default,
            picVer6: require('./OurCouplesPics/OlgaPiotr/ver7.jpg').default,
            picVer7: require('./OurCouplesPics/OlgaPiotr/ver6.jpg').default,
            picVer8: require('./OurCouplesPics/OlgaPiotr/ver8.jpg').default,
            picVer9: require('./OurCouplesPics/OlgaPiotr/ver9.jpg').default,
            picVer10: require('./OurCouplesPics/OlgaPiotr/ver5.jpg').default,
            classNameOne: "twoVertHoriz",
            classNameThree: "twoVertHorizFlipped",
            classNameFour: "twoVertHorizFlipped"
        }
    },
    {
        bgColor: "bgMint",
        title: "Ewelina & Łukasz",
        details: <><CustomPostLink text="Ślub kościelny" path="dokumenty-do-slubu-koscielnego-konkordatowego" className="bold" /> w cudownej parkowej scenerii. Srebro, transparentność, morze kwiatów i namiot. Glamour w najczystszej formie, łączący się z pięknem otaczającej natury.</>,
        org: "Agencja Ślubna Czary Marry",
        orgLink: "",
        place: "Pałac Pstrokonie",
        placeLink: "http://palac-pstrokonie.pl/",
        photo: "Wawrzykowski Team",
        photoLink: "https://wawrzykowski.pl/",
        flowers: "Florodesign",
        flowersLink: "https://floro.pl/",
        photos: {
            pic1: require('./OurCouplesPics/EwelinaLukasz/01.jpg').default,
            pic2: require('./OurCouplesPics/EwelinaLukasz/04.jpg').default,
            pic4: require('./OurCouplesPics/EwelinaLukasz/06.jpg').default,
            pic5: require('./OurCouplesPics/EwelinaLukasz/07.jpg').default,
            pic6: require('./OurCouplesPics/EwelinaLukasz/16.jpg').default,
            pic7: require('./OurCouplesPics/EwelinaLukasz/09.jpg').default,
            pic8: require('./OurCouplesPics/EwelinaLukasz/11.jpg').default,
            pic9: require('./OurCouplesPics/EwelinaLukasz/13.jpg').default,
            pic10: require('./OurCouplesPics/EwelinaLukasz/15.jpg').default,
            pic11: require('./OurCouplesPics/EwelinaLukasz/08.jpg').default,
            pic12: require('./OurCouplesPics/EwelinaLukasz/05.jpg').default,
            pic14: require('./OurCouplesPics/EwelinaLukasz/03.jpg').default,
            pic15: require('./OurCouplesPics/EwelinaLukasz/02.jpg').default,
            pic17: require('./OurCouplesPics/EwelinaLukasz/10.jpg').default,
            pic18: require('./OurCouplesPics/EwelinaLukasz/12.jpg').default,
            pic19: require('./OurCouplesPics/EwelinaLukasz/14.jpg').default,
            picVer3: require('./OurCouplesPics/EwelinaLukasz/ver1.jpg').default,
            classNameTwo: "threeHorizFlipped",
            classNameFive: "threeHoriz"
        }
    },
    {
        bgColor: "bgGrey",
        title: "Nelli & Piotr",
        details: "Wesele w stodole. Romantyczne dekoracje, piękna pogoda i strefa chill z barmanem na zewnątrz, a w niedzielę brunch połączony z leżakowaniem na trawie.",
        org: "Agencja Ślubna Czary Marry",
        orgLink: "",
        place: "Folwark Wąsowo",
        placeLink: "Folwark Wąsowo",
        photo: "Svetlana Bennington",
        photoLink: "http://svetlanabennington.com/",
        flowers: "ArtSize",
        flowersLink: "http://www.artsize.pl/",
        photos: {
            pic1: require('./OurCouplesPics/NellyPiotr/01.JPG').default,
            pic2: require('./OurCouplesPics/NellyPiotr/02.JPG').default,
            pic3: require('./OurCouplesPics/NellyPiotr/03.JPG').default,
            pic4: require('./OurCouplesPics/NellyPiotr/04.JPG').default,
            pic5: require('./OurCouplesPics/NellyPiotr/05.JPG').default,
            pic6: require('./OurCouplesPics/NellyPiotr/06.JPG').default,
            pic7: require('./OurCouplesPics/NellyPiotr/07.JPG').default,
            pic10: require('./OurCouplesPics/NellyPiotr/11.JPG').default,
            pic11: require('./OurCouplesPics/NellyPiotr/10.JPG').default,
            pic12: require('./OurCouplesPics/NellyPiotr/12.JPG').default,
            pic13: require('./OurCouplesPics/NellyPiotr/13.JPG').default,
            pic16: require('./OurCouplesPics/NellyPiotr/16.JPG').default,
            pic17: require('./OurCouplesPics/NellyPiotr/17.JPG').default,
            pic18: require('./OurCouplesPics/NellyPiotr/18.JPG').default,
            pic19: require('./OurCouplesPics/NellyPiotr/19.JPG').default,
            picVer1: require('./OurCouplesPics/NellyPiotr/ver01.jpg').default,
            picVer2: require('./OurCouplesPics/NellyPiotr/ver02.jpg').default,
            picVer3: require('./OurCouplesPics/NellyPiotr/ver03.jpg').default,
            picVer4: require('./OurCouplesPics/NellyPiotr/ver07.jpg').default,
            picVer5: require('./OurCouplesPics/NellyPiotr/ver06.jpg').default,
            picVer6: require('./OurCouplesPics/NellyPiotr/ver04.jpg').default,
            picVer7: require('./OurCouplesPics/NellyPiotr/ver8.jpg').default,
            classNameOne: "twoVertHorizFlipped",
            classNameTwo: "threeHoriz",
            classNameThree: "twoVertHorizFlipped",
            classNameFive: "threeHorizFlipped"
        }
    },
    {
        bgColor: "bgPink",
        title: "Basia & Mariusz",
        details: "Jesienne wesela mają w sobie magię. Mimo że za oknem zimno i szaro, nam udało się wyczarować niezwykły klimat. Pomógł nam półmrok za oknem, światło świec i odważne połączenie kolorów.",
        org: "Agencja Ślubna Czary Marry",
        orgLink: "",
        place: "Rezydencja Miętowe Wzgórza",
        placeLink: "http://www.mietowewzgorza.pl/wesela.html",
        photo: "Marta Brodziak",
        photoLink: "http://martabrodziak.com/",
        movie: "MW Jackiewicz",
        movieLink: "http://www.mwjackiewicz.com/",
        flowers: "Unique",
        flowersLink: "https://www.facebook.com/unique.pracownia/",
        photos: {
            pic1: require('./OurCouplesPics/BasiaMariusz/02.jpg').default,
            pic2: require('./OurCouplesPics/BasiaMariusz/01.jpg').default,
            pic3: require('./OurCouplesPics/BasiaMariusz/03.jpg').default,
            pic4: require('./OurCouplesPics/BasiaMariusz/04.jpg').default,
            pic5: require('./OurCouplesPics/BasiaMariusz/05.jpg').default,
            pic6: require('./OurCouplesPics/BasiaMariusz/09.jpg').default,
            pic7: require('./OurCouplesPics/BasiaMariusz/11.jpg').default,
            pic8: require('./OurCouplesPics/BasiaMariusz/12.jpg').default,
            pic9: require('./OurCouplesPics/BasiaMariusz/13.jpg').default,
            pic10: require('./OurCouplesPics/BasiaMariusz/06.jpg').default,
            pic11: require('./OurCouplesPics/BasiaMariusz/08.jpg').default,
            pic12: require('./OurCouplesPics/BasiaMariusz/07.jpg').default,
            pic16: require('./OurCouplesPics/BasiaMariusz/10.jpg').default,
            pic17: require('./OurCouplesPics/BasiaMariusz/14.jpg').default,
            picVer1: require('./OurCouplesPics/BasiaMariusz/ver3.jpg').default,
            picVer2: require('./OurCouplesPics/BasiaMariusz/ver1.jpg').default,
            picVer3: require('./OurCouplesPics/BasiaMariusz/ver2.jpg').default,
            picVer6: require('./OurCouplesPics/BasiaMariusz/ver5.jpg').default,
            picVer7: require('./OurCouplesPics/BasiaMariusz/ver4.jpg').default,
            picVer8: require('./OurCouplesPics/BasiaMariusz/ver6.jpg').default,
            picVer9: require('./OurCouplesPics/BasiaMariusz/ver7.jpg').default,
            classNameOne: "twoVertHoriz",
            classNameTwo: "threeHoriz",
            classNameThree: "twoVertHorizFlipped",
            classNameFour: "twoVertHorizFlipped"
        }
    },
    {
        bgColor: "bgGrey",
        title: "Marta & Marek",
        details: "Nowoczesność, elegancja, minimalizm i 1000 kalii.",
        org: "Agencja Ślubna Czary Marry",
        orgLink: "",
        place: "Hotel Wodnik",
        placeLink: "http://wodnik-hotel.pl/",
        photo: "Bauaban Fotografia",
        photoLink: "https://bauaban.com/",
        flowers: "ArtSize",
        flowersLink: "http://www.artsize.pl/",
        photos: {
            pic1: require('./OurCouplesPics/MartaMarek/01.jpg').default,
            pic2: require('./OurCouplesPics/MartaMarek/02.jpg').default,
            pic4: require('./OurCouplesPics/MartaMarek/04.jpg').default,
            pic5: require('./OurCouplesPics/MartaMarek/05.jpg').default,
            pic6: require('./OurCouplesPics/MartaMarek/06.jpg').default,
            pic7: require('./OurCouplesPics/MartaMarek/07.jpg').default,
            pic8: require('./OurCouplesPics/MartaMarek/08.jpg').default,
            pic9: require('./OurCouplesPics/MartaMarek/09.jpg').default,
            pic10: require('./OurCouplesPics/MartaMarek/10.jpg').default,
            pic11: require('./OurCouplesPics/MartaMarek/12.jpg').default,
            pic12: require('./OurCouplesPics/MartaMarek/11.jpg').default,
            pic13: require('./OurCouplesPics/MartaMarek/13.jpg').default,
            pic14: require('./OurCouplesPics/MartaMarek/14.jpg').default,
            pic15: require('./OurCouplesPics/MartaMarek/15.jpg').default,
            picVer3: require('./OurCouplesPics/MartaMarek/ver3.jpg').default,
            picVer4: require('./OurCouplesPics/MartaMarek/ver4.jpg').default,
            picVer5: require('./OurCouplesPics/MartaMarek/ver5.jpg').default,
            classNameTwo: "threeHoriz"
        }
    },
    {
        bgColor: "bgMint",
        title: "Angie & Akshar",
        details: "To było typowe slow wedding. Goście spędzali czas na zewnątrz rozmawiając, grając w gry, popijając drinki. Było kameralnie i rodzinnie, czyli tak jak lubimy najbardziej.",
        org: "Agencja Ślubna Czary Marry",
        orgLink: "",
        place: "Folwark Białych Bocianów",
        placeLink: "https://www.folwarkbb.com/",
        photo: "Greg Solak",
        photoLink: "http://www.gregsolak.pl/Blog/",
        movie: "Greg Solak",
        movieLink: "http://www.gregsolak.pl/Blog/",
        flowers: "Marlena Chustecka",
        flowersLink: "https://www.facebook.com/pages/category/Artist/Chustecka-Marlena-1077253032301187/",
        photos: {
            pic1: require('./OurCouplesPics/AngieAkshar/01.jpg').default,
            pic2: require('./OurCouplesPics/AngieAkshar/02.jpg').default,
            pic4: require('./OurCouplesPics/AngieAkshar/04.jpg').default,
            pic5: require('./OurCouplesPics/AngieAkshar/05.jpg').default,
            pic6: require('./OurCouplesPics/AngieAkshar/06.jpg').default,
            pic7: require('./OurCouplesPics/AngieAkshar/07.jpg').default,
            pic8: require('./OurCouplesPics/AngieAkshar/08.jpg').default,
            pic9: require('./OurCouplesPics/AngieAkshar/09.jpg').default,
            pic10: require('./OurCouplesPics/AngieAkshar/10.jpg').default,
            pic11: require('./OurCouplesPics/AngieAkshar/11.jpg').default,
            pic12: require('./OurCouplesPics/AngieAkshar/12.jpg').default,
            pic14: require('./OurCouplesPics/AngieAkshar/14.jpg').default,
            pic15: require('./OurCouplesPics/AngieAkshar/15.jpg').default,
            pic17: require('./OurCouplesPics/AngieAkshar/17.jpg').default,
            pic18: require('./OurCouplesPics/AngieAkshar/18.jpg').default,
            pic19: require('./OurCouplesPics/AngieAkshar/19.jpg').default,
            picVer10: require('./OurCouplesPics/AngieAkshar/ver10.jpg').default,
            classNameTwo: "threeHorizFlipped",
            classNameFive: "threeHoriz"
        }
    }
]

export default weddings