import main from "./main.jpg"
import butyNaWesJes from "./buty-na-wesele-jesienia.jpg"
import jakiKolSuk from "./jaki-kolor-sukienki.jpg"
import jesDekoKość from "./jesienna-dekoracja-kosciola.jpg"
import jesWes01 from "./jesienne-wesele-01.jpg"
import jesWes02 from "./jesienne-wesele-02.jpg"
import jesWes03 from "./jesienne-wesele-03.jpg"
import jesWes03A from "./jesienne-wesele-03a.jpg"
import jesWes04 from "./jesienne-wesele-04.jpg"
import jesWes05 from "./jesienne-wesele-05.jpg"
import jesWes06 from "./jesienne-wesele-06.jpg"
import jesWes07 from "./jesienne-wesele-07.jpg"
import jesWes08 from "./jesienne-wesele-08.jpg"
import jesWes09 from "./jesienne-wesele-09.jpg"
import jesWes10 from "./jesienne-wesele-10.jpg"
import jesWes11 from "./jesienne-wesele-11.jpg"
import jesWes12 from "./jesienne-wesele-12.jpg"
import jesWes13 from "./jesienne-wesele-13.jpg"
import jesWes14 from "./jesienne-wesele-14.jpg"
import jesWes15 from "./jesienne-wesele-15.jpg"
import jesWes16 from "./jesienne-wesele-16.jpg"
import jesWesInsp from "./jesienne-wesele-inspiracje.jpg"
import motPrzewWeJes from "./motyw-przewodni-wesela-jesien.jpg"
import stylNaWesJes from "./stylizacje-na-wesele-jesienia.jpg"
import sukienkaNaJesWes from "./sukienka-na-jesienne-wesele.jpg"
import sukienkiNaWesJes from "./sukienki-na-wesele-jesienia.jpg"
import wesJes01 from "./wesele-jesienia-01.jpg"
import wesJes02 from "./wesele-jesienia-02.jpg"
import wesJes03 from "./wesele-jesienia-03.jpg"
import wesJes04 from "./wesele-jesienia-04.jpg"
import wesJes05 from "./wesele-jesienia-05.jpg"
import zaprNaSlubJes01 from "./zaproszenia-na-slub-jesienia-01.jpg"
import zaprNaSlubJes02 from "./zaproszenia-na-slub-jesienia-02.jpg"
import zaprNaSlubJes03 from "./zaproszenia-na-slub-jesienia-03.jpg"

export { jakiKolSuk, jesDekoKość, jesWes01, jesWes02, jesWes03, jesWes03A, jesWes04, jesWes05, jesWes06, jesWes07, jesWes08, jesWes09, jesWes10, jesWes11, jesWes12, jesWes13, jesWes14, jesWes15, jesWes16, jesWesInsp, main, motPrzewWeJes, stylNaWesJes, sukienkaNaJesWes, sukienkiNaWesJes, zaprNaSlubJes01, zaprNaSlubJes02, zaprNaSlubJes03, wesJes01, wesJes02, wesJes03, wesJes04, wesJes05, butyNaWesJes }


