import main from "./main.jpg"
import slowWed01 from "./slow-wedding-01.jpg"
import slowWed02 from "./slow-wedding-02.jpg"
import slowWed03 from "./slow-wedding-03.jpg"
import slowWed04 from "./slow-wedding-04.jpg"
import slowWed05 from "./slow-wedding-05.jpg"
import slowWed06 from "./slow-wedding-06.jpg"
import slowWed07 from "./slow-wedding-07.jpg"
import slowWed08 from "./slow-wedding-08.jpg"
import slowWed09 from "./slow-wedding-09.jpg"
import slowWed10 from "./slow-wedding-10.jpg"
import slowWed11 from "./slow-wedding-11.jpg"
import slowWed12 from "./slow-wedding-12.jpg"
import slowWed13 from "./slow-wedding-13.jpg"
import slowWed14 from "./slow-wedding-14.jpg"
import slowWed15 from "./slow-wedding-15.jpg"
import wesLuz01 from "./wesele-na-luzie-01.jpg"
import wesLuz02 from "./wesele-na-luzie-02.jpg"
import wesLuz03 from "./wesele-na-luzie-03.jpg"
import wesLuz04 from "./wesele-na-luzie-04.jpg"
import wesLuz05 from "./wesele-na-luzie-05.jpg"
import wesLuz06 from "./wesele-na-luzie-06.jpg"
import wesLuz07 from "./wesele-na-luzie-07.jpg"
import wesLuz08 from "./wesele-na-luzie-08.jpg"
import wesSlow01 from "./wesele-w-stylu-slow-01.jpg"
import wesSlow02 from "./wesele-w-stylu-slow-02.jpg"
import wesSlow03 from "./wesele-w-stylu-slow-03.jpg"
import wesSlow04 from "./wesele-w-stylu-slow-04.jpg"
import wesSlow05 from "./wesele-w-stylu-slow-05.jpg"
import wesSlow06 from "./wesele-w-stylu-slow-06.jpg"
import wesSlow07 from "./wesele-w-stylu-slow-07.jpg"
import wesSlow08 from "./wesele-w-stylu-slow-08.jpg"


export { main, slowWed01, slowWed02, slowWed03, slowWed04, slowWed05, slowWed06, slowWed07, slowWed08, slowWed09, slowWed10, slowWed11, slowWed12, slowWed13, slowWed14, slowWed15, wesLuz01, wesLuz02, wesLuz03, wesLuz04, wesLuz05, wesLuz06, wesLuz07, wesLuz08, wesSlow01, wesSlow02, wesSlow03, wesSlow04, wesSlow05, wesSlow06, wesSlow07, wesSlow08 }