import angPaw01 from "../AngelikaPawel/01.jpg"
import angPaw02 from "../AngelikaPawel/02.jpg"
import angPaw03 from "../AngelikaPawel/03.jpg"
import angPaw04 from "../AngelikaPawel/04.jpg"
import angPaw05 from "../AngelikaPawel/05.jpg"
import angPaw06 from "../AngelikaPawel/06.jpg"
import angPaw07 from "../AngelikaPawel/07.jpg"
import angPaw08 from "../AngelikaPawel/08.jpg"
import angPaw09 from "../AngelikaPawel/09.jpg"
import angPaw10 from "../AngelikaPawel/10.jpg"
import angPaw11 from "../AngelikaPawel/11.jpg"
import angPaw12 from "../AngelikaPawel/12.jpg"
import angPaw16 from "../AngelikaPawel/16.jpg"
import angPaw17 from "../AngelikaPawel/17.jpg"
import angPaw18 from "../AngelikaPawel/18.jpg"
import angPaw19 from "../AngelikaPawel/19.jpg"
import angPawVer02 from "../AngelikaPawel/ver2.jpg"
import angPawVer03 from "../AngelikaPawel/ver3.jpg"
import angPawVer04 from "../AngelikaPawel/ver4.jpg"
import angPawVer06 from "../AngelikaPawel/ver6.jpg"
import angPawVer07 from "../AngelikaPawel/ver7.jpg"

export { angPaw01, angPaw02, angPaw03, angPaw04, angPaw05, angPaw06, angPaw07, angPaw08, angPaw09, angPaw10, angPaw11, angPaw12, angPaw16, angPaw17, angPaw18, angPaw19, angPawVer02, angPawVer03, angPawVer04, angPawVer06, angPawVer07 }
